# Generated by Django 3.0.6 on 2020-05-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCurso', models.CharField(max_length=100, verbose_name='Id do curso')),
                ('quantidadeHomens', models.CharField(max_length=100, verbose_name='Quantidade Homens')),
                ('quantidadeMulheres', models.CharField(max_length=100, verbose_name='Quantidade Mulheres')),
            ],
        ),
    ]
